# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9527d4cc07e63163ebadb99056cfc4ed8f1099b3d364d79e660550b3f5e1e1f744dee402fcf67102ec446ef447adb66e45fc0709a5b090e001937af14f2b165d

test:
  secret_key_base: 5db5f40b52a4cc0da1e59264255ca67c05dca318d3a83450595faf297b5d1b696a2e31fa9aa2c1566fcc34bd4b087c2f3b832196e5a16727c8b41878f04c2999

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
